### PR TITLE
Added conntrack stats script

### PR DESCRIPTION
**Pull request by angryp**
This commit applies support for conntrack metrics gathering from Netfilter. 
Originally, this was posted by @redneon in Cacti forums: https://forums.cacti.net/viewtopic.php?f=12&t=36629
I did reach out the author via e-mail and received his approval to redistribute the code, so here is the first step. LibreNMS core support commit is on it's way.

### CODE REVIEW

**Comment by laf** [comment]
Thanks for this. One thing we are trying to do is convert these to use json.

@VVelox Might be able to help get that done.

**Comment by VVelox** [comment]
@laf Ohh! Thanks. This looks like fun. That said sorry about disappearing and thanks for summoning me. :)

**Comment by angryp** [comment]
Hello @laf and @VVelox!

Will you require any assistance from my side?

**Comment by PipoCanaja** [comment]
@VVelox : What is the status of this PR ?

**Comment by bnerickson** [comment]
Hi @angryp @Jellyfrog @VVelox .  Can we get a re-execution of the tests for this PR?  I don't mind submitting it myself to get the ball rolling and fix the Lint issues if that's OK with @angryp  :)

**Comment by bnerickson** [comment]
Thanks, @Jellyfrog 

I think I'm going to tackle this with a new, separate python script that queries the "ss" utility instead of "conntrack".  It wasn't hard updating the perl script to output the data in JSON, but the "ss" utility replaces conntrack and the perl script doesn't grab TCP LISTENING port statistics which is the kiss of death imo.  Besides, I think I can code it to be a bit more readable in python vs perl which I've always found to be a bit harder to parse.

Anyway, if someone REALLY wants to get this perl script merged and add an application supporting it; I've attached the modified script here.  It's basically done (note that it requires the perl JSON module now).

[conntrack.pl.txt](https://github.com/librenms/librenms-agent/files/11547575/conntrack.pl.txt)

**Pull request closed without merging**
