### PR TITLE
add check_mrpe script

### PR DESCRIPTION
**Pull request by slashdoom**
Script to allow checking Check_MK agent MRPE as a service.

### CODE REVIEW

**Comment by TheGreatDoc** [comment]
@slashdoom please sign the CLA!

**Comment by slashdoom** [comment]
I have signed and rechecked.   Not sure why I can't remove that flag.

**Comment by TheGreatDoc** [comment]
Ok. Doesnt matters. Do you mind setting up some doc on how this works?

**Comment by slashdoom** [comment]
PR for documentation submitted.
https://github.com/librenms/librenms/pull/11834

**Pull request merged**
