### PR TITLE
Tchmnkyz patch 1

### PR DESCRIPTION
**Pull request by tchmnkyz**
I had problems with the scripts working on some debian based systems. To fix it i used the following. Thought I would share it so others might not have the same problem.

### CODE REVIEW

**Comment by crcro** [comment]
@tchmnkyz ... those value should be changed by each user individually based on their distro layout, changing them as you did it would render them useless on other os distros.

**Comment by tchmnkyz** [comment]
@crcro, Actually i checked multiple distro's before i submitted this. Freebsd, Debian, CentOS, Redhat all had the same path to which. This means that it should work on most distributions without too many issues.

**Comment by murrant** [comment]
What is the point of using which here?  Just put the commands without the the path and it does exactly the same thing.

Also, why do we use full path in the first place?

**Comment by PipoCanaja** [comment]
Should we continue in this PR or just remove full path here and trust SNMPd PATH definition to find the binaries ?

**Comment by SourceDoctor** [comment]
Binarypathes can be overwritten if needed

`...
CONFIG=$0".conf"
if [ -f $CONFIG ]; then
    . $CONFIG
fi
....
`
so no need for PR

**Pull request closed without merging**
