### PR TITLE
extend: powerdns-dnsdist

### PR DESCRIPTION
**Pull request by crcro**
snmp extend script needed for powerdns-dnsdist support

### CODE REVIEW

**Comment by murrant** [comment]
Why are you processing the data here?  Just dump it and process it in LibreNMS.

Also, the powerdns_recursor script allows direct api access.

**Comment by crcro** [comment]
the api response only reports incremental values (not last values since last poll)

**Comment by murrant** [comment]
Then use counter rrd type?

**Comment by crcro** [comment]
i meant that you would get only an up line every pool (like uptime graph), not very useful, i think that queries per 5 minute graph is better that 100 queries 10 minutes ago, 192 queries 5 minutes ago, 203 queries now graph.

**Pull request merged**
