### PR TITLE
Add snmp script for BeagleBoard Temperature Sensors

### PR DESCRIPTION
**Pull request by arrmo**
Add a new snmp script, similar to Raspberry Pi sensors, but this is for BeagleBoard. Output from the command (example),
```
$ beagleboard.sh
40200
41400
40600
39800
41000
```

Thanks!

### CODE REVIEW

**Comment by SourceDoctor** [comment]
Hi,
not sure, to which Application PR or OS PR in [LibreNMS](https://github.com/librenms/librenms/pulls) is this PR refering to?

**Comment by arrmo** [comment]
Sorry, it's for https://github.com/librenms/librenms/pull/12060

Thanks!

**Comment by SourceDoctor** [comment]
agents should communicate via JSON to LibreNMS Server

structure:

`{'version': 1, 'error': 0, 'errorString': '', 'data': <your data in structure you like/need/prefer>}`

**Comment by arrmo** [comment]
Sorry, wasn't aware of that (as some scripts like distro don't do that, do they?) - is this something new?

Thanks!

**Comment by SourceDoctor** [comment]
no problem,
distro is in old style :-)

**Comment by arrmo** [comment]
I'm old style ... LMAO. NP, will try to get this modified, thanks.

**Comment by SourceDoctor** [comment]
LOL
here is an example
https://github.com/librenms/librenms/blob/master/includes/polling/applications/mdadm.inc.php

**Pull request merged**
