### PR TITLE
Fix: Update pi-hole app for new API

### PR DESCRIPTION
**Pull request by slashdoom**

### CODE REVIEW

**Comment by FingerlessGlov3s** [comment]
Any news of this PR?
My LibreNMS reports records incorrectly, I highly doubt I'm doing 28k PTR records lol.
image

**Comment by SourceDoctor** [comment]
@FingerlessGlov3s @slashdoom 
have you tried new pi-hole Agent? does it solve your need?

**Comment by FingerlessGlov3s** [comment]
When did the update come in? Currently it's still broken but I am on monthly update not daily.

**Comment by SourceDoctor** [comment]
before some days the agent script update comes in. 
it's irrelevant on which update tree you are. Agent Scripts are your problem ;-)

**Pull request closed without merging**
