### PR TITLE
Correct error zpool command

### PR DESCRIPTION
**Pull request by Cormoran96**
Zpool list option is P Uppercase not lowercase

### CODE REVIEW

**Comment by laf** [comment]
this seems to vary :(

```
[root@nas2] ~# zpool list -PH
invalid option 'P'
usage:
	list [-Hpv] [-o property[,...]] [-T d|u] [pool] ... [interval [count]]
```

**Comment by Cormoran96** [comment]
```bash
root@miraz:[~]#` lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
root@miraz:[~]# zpool list -pH
invalid option 'p'
usage:
	list [-gHLPv] [-o property[,...]] [-T d|u] [pool] ... [interval [count]]
```

So bad news 😢

**Comment by laf** [comment]
If the exit code for that is non-zero then check that and run the original command (or vice versa)

**Comment by Zmegolaz** [comment]
My zpool has both. :) 
`list [-gHLpPv] [-o property[,...]] [-T d|u] [pool] ... [interval [count]]`

From the manual:
```
             -p      Display numbers in parsable (exact) values.
             -P      Display full paths for vdevs instead of only the last component of the path. This can be used in conjunction with the -L -flag.
```
Some check that the output is what's expected seems to be needed. @Cormoran96 , what switch is used in your version to display exact numbers?

**Comment by Cormoran96** [comment]
It is
```
zpool list [-T d | u] [-HgLPv] [-o props[,...]] [pool] ... [interval[count]]
           -P          Display full paths for vdevs instead of only the last component of the path.  This can be used in conjunction with the -L flag.
```
```
zpool get [-p] "all" | property[,...] pool ...
           -p    Display numbers in parseable (exact) values.


```

**Comment by Zmegolaz** [comment]
`zpool get -p` is different from `zpool list -p`. `list` show a list of pools, while `get` show properties for the pools. This script want the list of pools. What does your `zpool list -H` look like?

**Comment by Cormoran96** [comment]
it look like this:

```
root@miraz:[~]# zpool list -H
data	1.81T	83.1G	1.73T	-	2%	4%	1.00x	ONLINE	-
```

**Comment by Zmegolaz** [comment]
I basically see two ways forward:

1. See if you run an old version of the zfsutils-linux package (or what it's called in your dist, whichever provides the `zpool` command) and update it.
2. Modify this script to check if the -p flag exists, otherwise calculate what the suffixes `k`, `M`, and so on means.

Any other ideas?

**Comment by Cormoran96** [comment]
Moved to  #213

**Pull request closed without merging**
