### PR TITLE
certificate file validity check

### PR DESCRIPTION
**Pull request by SourceDoctor**
certificate monitoring
- age
- remaining days valid

fill out a certificate file with certificates to be monitored:

/etc/snmp/certificate.json
```
{"domains": [
    {"fqdn": "www.mydomain.com"},
    {"fqdn": "www2.mydomain.com"}
]
}
```

### CODE REVIEW

**Comment by SourceDoctor** [comment]
something else to handle on this Extension?

**Comment by laf** [comment]
I get this when I try to run it:

```
Traceback (most recent call last):
  File "ssl.py", line 4, in <module>
    import ssl
  File "/root/ssl.py", line 55, in <module>
    certificate_data, error_msg = get_certificate_data(domain['fqdn'], domain['port'])
  File "/root/ssl.py", line 19, in get_certificate_data
    context = ssl.create_default_context()
AttributeError: 'module' object has no attribute 'create_default_context'
```

**Comment by SourceDoctor** [comment]
I'm a little bit confused about this error.
is Debian/Ubuntu Package 'python3-openssl' Package installed?

**Comment by SourceDoctor** [comment]
@laf
?

**Comment by SourceDoctor** [comment]
@laf 
i cannot help you if you not help me debugging ;-)

**Comment by laf** [comment]
Sorry @SourceDoctor. Not really been active that much :/

**Pull request merged**
