### PR TITLE
update the fail2ban stuff

### PR DESCRIPTION
**Pull request by VVelox**
This is for a shortly incoming update to the fail2ban polling.

### CODE REVIEW

**Comment by karlshea** [comment]
This update breaks on Ubuntu 16.04 when not running as root:

```
root@citywall:/etc/snmp# ./fail2ban
1
sshd 1
sshd-ddos 0
root@citywall:/etc/snmp# sudo -i -u librenms /etc/snmp/fail2ban
ERROR  Permission denied to socket: /var/run/fail2ban/fail2ban.sock, (you must be root)
Use of uninitialized value $jailsS in substitution (s///) at /etc/snmp/fail2ban line 105.
Use of uninitialized value $jailsS in substitution (s///) at /etc/snmp/fail2ban line 106.
Use of uninitialized value $jailsS in split at /etc/snmp/fail2ban line 107.
0
```

**Comment by murrant** [comment]
I think this means you weren't fully collecting the data before.

Give the snmp user read access to the socket perhaps?

**Comment by karlshea** [comment]
image

It was working until I pulled the latest librenms-agent, including both jails.

**Comment by karlshea** [comment]
If I set the socket to world rwx it does continue to work, but that might need to be part of the app's installation instructions.

**Comment by murrant** [comment]
Odd that there was any change as that was outside of the script.  The fail2ban-client is used for both scripts.

An update to the docs would be appreciated, but it would need to be more generally applicable.

**Comment by karlshea** [comment]
It is odd, I don't really have an explanation. I half-heartedly looked through the diff and saw it was using iptables before too, but calling iptables as the snmp user doesn't work either.

**Comment by VVelox** [comment]
This script required using sudo to to call it on some systems previously.

**Pull request merged**
