### PR TITLE
Fix osupdate script broken by #444

### PR DESCRIPTION
**Pull request by jepke**
#444  broke osupdate script through snmp extend

### CODE REVIEW

**Comment by JamesMenetrey** [comment]
Hello,

While I'm unsure this is the right approach to fix this issue, I confirm this patch solves an issue where LibreNMS cannot pull the number of updates properly.

@VVelox This would be cool if you could look into it, as in the current state, the osupdate does not work.

Cheers!

**Comment by VVelox** [comment]
@JamesMenetrey Sure! Looking.

**Comment by VVelox** [comment]
Confirmed.  This only works with the older extend with out that line. The LibreNMS commit in relationship to this only passed as there are no relevant tests to make sure it did not fail.

**Comment by VVelox** [comment]
Added a line to uncomment to use it as a agent. https://github.com/librenms/librenms-agent/pull/471

**Comment by JamesMenetrey** [comment]
Many thanks for your quick feedback!

**Pull request merged**
