### PR TITLE
make ntp-client.sh dd-wrt(with ipkg) friendly and remove bash requirement

### PR DESCRIPTION
**Pull request by VVelox**
Yes, I've signed the author stuff etc... For some reason this form is not present here...

Wooho!

For DD-WRT, install ntp via ipkg as ntpq does not come in the base.

root@wap0:/jffs/snmpd# ./ntp-client
50.060777
-8.028
29.335078
8.745
0.012
root@wap0:/jffs/snmpd#

### CODE REVIEW

**Comment by VVelox** [comment]
Rewrote with out the bash stuff as for some reason it was choking on that with the version of bash available via ipkg. Tested on FreeBSD and this works there as well.

**Comment by rockyluke** [comment]
On Debian and Ubuntu, **/bin/sh** is ash which is very limited. Maybe we need to find a better way to be full compatible for BSD and Linux ?

**Comment by VVelox** [comment]
No advanced shell stuff is required and this was tested on ash(DD-WRT). Also this is not a BSD v. Linux issue. This is specifically that it does not work with DD-WRT and the version of bash available via ipkg.

**Comment by rockyluke** [comment]
That's not what I meant...

That's OK for me :-)

**Comment by VVelox** [comment]
Okay. I am confused then. =^.^=

**Pull request closed without merging**
