### PR TITLE
add zfs support for linux

### PR DESCRIPTION
**Pull request by Serphentas**
This is just to bring support for ZFS probing on Linux devices where SPL is used with ZoL.

It's basically a Python rewrite of [zfs-freebsd](https://github.com/librenms/librenms-agent/blob/master/snmp/zfs-freebsd) using some parts of the code written by @tracernz in #166.

### CODE REVIEW

**Comment by laf** [comment]
Thanks for this @Serphentas. I assume this outputs the same as the freebsd version?

Can you also update the docs here to show a linux version is available along with the instructions to install: https://github.com/librenms/librenms/blob/master/doc/Extensions/Applications.md#zfs

**Comment by Serphentas** [comment]
@laf You're welcome. As for the output, I've made sure all JSON keys read in the [poller code](https://github.com/librenms/librenms/blob/master/includes/polling/applications/zfs.inc.php) are present and correct.

Sure, will update docs now.

**Comment by laf** [comment]
@Serphentas All good to go on this PR?

**Comment by Serphentas** [comment]
@laf Yes you can go ahead and merge. I just committed a quick fix.

Also, to note is that the `-p` parameter for the `zpool list` is not available on all ZFS versions, or at least not with version `0.6.5.6-0ubuntu16`.

As for the documentation, see https://github.com/librenms/librenms/pull/8546.

**Pull request merged**
